# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 알파스탯의 통계이야기
email: secondmath85@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jannik Richter, jannik811@gmail.com
baseurl: "/jekyll-slender-template" # the subpath of your site, e.g. /blog
url: "http://alphastat.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  alphastat

# Build settings
markdown: kramdown
