# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: statstory by alphastat
email: secondmath85@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alphastat.github.io" # the base hostname & protocol for your site
author: Jinseob Kim

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
paginate: 5
paginate_path: 'page:num/'
comments: true
excerpt_separator: <!-- more -->
